name: Upload WebApp to Azure Storage

on:
  push:
  workflow_dispatch:

jobs:
  update-storage:
    runs-on: ubuntu-latest
    environment: ${{ contains(github.ref_name, 'dev') && 'dev' || '' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Azure Blob Storage
      run: |
        az storage blob upload-batch -s ./webapp -d https://safestoragedev.blob.core.windows.net/webcontent --auth-mode login

    - name: Logout of Azure
      run: az logout
